# Generated by Django 3.2.4 on 2021-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stopID', models.IntegerField(primary_key=True, serialize=False)),
                ('stopName', models.CharField(max_length=50, null=True)),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_time', models.IntegerField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('rain', models.BooleanField()),
                ('icon', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'futureweather',
            },
        ),
        migrations.CreateModel(
            name='RouteStops',
            fields=[
                ('routeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=1)),
                ('stopID', models.IntegerField()),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'routestops',
                'unique_together': {('routeID', 'direction', 'stopID')},
            },
        ),
    ]
