# Generated by Django 3.2.4 on 2021-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stopID', models.IntegerField(primary_key=True, serialize=False)),
                ('stopName', models.CharField(max_length=50, null=True)),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='RouteStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeID', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=1)),
                ('stopID', models.IntegerField()),
            ],
            options={
                'db_table': 'route_stops',
                'unique_together': {('routeID', 'direction', 'stopID')},
            },
        ),
    ]
