# Generated by Django 3.2.4 on 2021-07-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteStops',
        ),
        migrations.DeleteModel(
            name='Stops',
        ),
    ]
