# Generated by Django 3.2.4 on 2021-07-19 20:08

import backend.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_old_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RouteNames',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=15)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routenames')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=15)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sequence', models.IntegerField()),
                ('dist_traveled', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('external_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=50)),
                ('headsign', models.CharField(max_length=150)),
                ('direction', models.IntegerField(choices=[(backend.api.models.Direction['INBOUND'], 'inbound'), (backend.api.models.Direction['OUTBOUND'], 'outbound')])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routes')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shapes')),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_sequence', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_headsign', models.CharField(max_length=30, null=True)),
                ('pickup_type', models.IntegerField(choices=[(0, 'Regular'), (1, 'Not available'), (2, 'Phone agency'), (3, 'Coordinate with driver')])),
                ('drop_off_type', models.IntegerField(choices=[(0, 'Regular'), (1, 'Not available'), (2, 'Phone agency'), (3, 'Coordinate with driver')])),
                ('shape_dist_traveled', models.FloatField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stops')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trips')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExceptions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exception_type', models.IntegerField(choices=[(1, 'Service added'), (2, 'Service removed')])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStops',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direction', models.IntegerField(choices=[(backend.api.models.Direction['INBOUND'], 'inbound'), (backend.api.models.Direction['OUTBOUND'], 'outbound')])),
                ('main', models.BooleanField()),
                ('sequence', models.IntegerField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routenames')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stops')),
            ],
        ),
    ]
