# Generated by Django 3.2.4 on 2021-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_gtfs_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='long_name',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
