# Generated by Django 3.2.4 on 2021-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fix_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='routes_names',
            field=models.ManyToManyField(related_name='stops', through='api.RouteStops', to='api.RouteNames'),
        ),
    ]
