# Generated by Django 3.2.4 on 2021-07-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_weather_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestops',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.agency'),
            preserve_default=False,
        ),
    ]
