# Generated by Django 3.2.4 on 2021-07-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_routestops_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestops',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shapes'),
        ),
    ]
