# Generated by Django 3.2.4 on 2021-08-19 13:42

import backend.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210729_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionBounds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direction', models.IntegerField(choices=[(backend.api.models.Direction['INBOUND'], 'inbound'), (backend.api.models.Direction['OUTBOUND'], 'outbound')])),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routenames')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stops')),
            ],
        ),
        migrations.DeleteModel(
            name='Realtime',
        ),
    ]
